### ISSUE TITLE
Mettre à jour Hunspell

### ISSUE THREAD

**Issue by FranckRJ** [FranckRJ/RespawnIRC#20]

**Comment by FranckRJ** [comment]
Bon, alors au final j'ai réussis à avoir une version d'Hunspell à jour et qui fonctionne avec des dico UTF-8, le problème c'est que ça obligera les gens qui veulent compiler RespawnIRC à compiler d'abord Hunspell, ce qui complique les choses et réduira forcément le nombre de personnes compilant le programme.

Donc je sais pas quoi faire, soit je mets pas à jour Hunspell, soit je le màj et je fournie une .dll dans la release mais rien dans les sources, soit je le màj en essayant de faire comme actuellement (Hunspell est dans les sources, et se compile en même temps que le programme pour tout le monde).

**Comment by LEpigeon888** [comment]
Avec ff532cc6606a62cbc61227a0aee9f64ba780576c Hunspell n'est plus contenu dans RespawnIRC, donc n'importe quelle version peut-être utilisée.

**Comment by FranckRJ** [comment]
Avec ff532cc6606a62cbc61227a0aee9f64ba780576c Hunspell n'est plus contenu dans RespawnIRC, donc n'importe quelle version peut-être utilisée, mais ça nécessite donc de compiler Hunspell avant de compiler RespawnIRC.
