### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: webenginewidgets

### ISSUE THREAD

**Issue by lucienleguellec** [FranckRJ/RespawnIRC#59]
Monsieur,

utilisateur de votre programme depuis sa sortie et néophyte de Linux, j'ai souhaité l'ajouter à mon debian fraichement installé afin de continuer de m'en servir comme sur Windows. J'ai suivi les instructions du Wiki mais, au moment d'exécuter la commande `qmake`, le système m'annonce qu'il ne connaît pas le modulre webenginewidgets, ainsi que l'annonce mon titre. J'ai installé le paquet libqt5webengine5 entertemps mais le problème persiste. Mes recherches ont ouvert quelques pistes dont aucune n'a malheureusement été fructueuse. Que puis-je faire ?

Soyez assuré de toute ma considération.

Lucien Le Guellec

**Comment by FranckRJ** [comment]
Visiblement il faudrait le paquet `qtwebengine5-dev`.

**Comment by lucienleguellec** [comment]
Grand merci pour votre réponse rapide, c'est visiblement ce qu'il fallait, mais j'ai maintenant un autre problème. Après avoir lancé la commande `make`, j'ai cette erreur :
`webNavigator.cpp: In constructor ‘webNavigatorClass::webNavigatorClass(QWidget*, QString, QList<QNetworkCookie>)’:
webNavigator.cpp:17:53: error: ‘setWindowFlag’ was not declared in this scope
     setWindowFlag(Qt::WindowMaximizeButtonHint, true);
                                                     ^
Makefile:1012 : la recette pour la cible « webNavigator.o » a échouée
make: *** [webNavigator.o] Erreur 1
`
C'est visiblement lié mais beaucoup plus pointu. Avez-vous une idée du problème ? Subsidiairement, peut-on supprimer simplement la fonction navigateur sans causer d'erreur de compilation ? Je ne m'en sers pas, de toute manière.

Encore merci.

**Comment by FranckRJ** [comment]
Normalement c'est corrigé dans les dernières sources de la branche master (https://github.com/FranckRJ/RespawnIRC/archive/master.zip), tu peux confirmer ?

**Comment by lucienleguellec** [comment]
C'est réglé, merci !
