### ISSUE TITLE
Une version AppImage pour Linux est-elle à venir ?

### ISSUE THREAD

**Issue by awsms** [FranckRJ/RespawnIRC#60]
https://github.com/AppImage/AppImageKit : ok :

**Comment by FranckRJ** [comment]
Non c'est pas prévu, je pense pas que le logiciel soit trop compliqué à compiler pour linux.

**Comment by awsms** [comment]
Et bien justement le quai mosellan, j'ai un problème lors de la compilation sur Linux

J'ai plus l'erreur exacte en tête, mais QT ne trouvait pas la libraire hunspell
J'ai suivi les conseils du wiki étape par étape, mais rien n'y fait

**Comment by FranckRJ** [comment]
Tu as bien regardé cette page https://github.com/FranckRJ/RespawnIRC/wiki/Compiler-Hunspell ?

Tu dois installer Hunspell depuis les dépôts et modifier 3 lignes du fichier respawnIrc.pro (comme décrit à la fin de la page du wiki).
