### ISSUE TITLE
Comment fermer un onglet?

### ISSUE THREAD

**Issue by awsms** [FranckRJ/RespawnIRC#61]
Excuse-moi Frank pour la question conne, mais j'ai pas encore trouver moyen de fermer un onglet, ce qui fait qu'à chaque fois que j'ouvre l'application je me trouve avec une vingtaine d'onglets ouverts.

Existe-t-il un raccourci clavier (Ctrl+W par ex) pour fermer rapidement un onglet?

**Comment by FranckRJ** [comment]
Il n'y a pas de raccourci pour éviter de fermer un onglet sans le vouloir, mais tu peux simplement cliquer sur la croix à côté du nom de l'onglet pour le fermer.
