### ISSUE TITLE
Les photos de profils se chargent plusieurs fois

### ISSUE THREAD

**Issue by zeid0ne** [FranckRJ/RespawnIRC#64]
Mettons que zeid0ne poste 5 messages sur la même page. On va charger sa photo de profil 5 fois. Il faudrait télécharger son image une seule fois, afficher cette unique image 5 fois pour économiser de la bande passante.

**Comment by FranckRJ** [comment]
Non les images ne sont téléchargées qu'une fois et ne sont pas re-téléchargées tant qu'elles sont dans le cache.
